[package]
name = "gif-displayer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ascii_displayer = { path = "../cake-sort/ascii_displayer" }
gif = "0.12.0"
termion = "2.0.1"
